# Nombre de la aplicaci n
spring.application.name=BackendMovil

# Conexi n inicial al contenedor PostgreSQL (base 'postgres' por defecto)
spring.datasource.url=jdbc:postgresql://localhost:5433/Back_Movil 
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci n de JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuraci n del servidor
server.port=9000

# Configuraci n de Swagger con Springdoc OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html